env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS=creds/travis-ci.json
  - PATH=$HOME/bin:$PATH
language: bash
before_install:
- openssl aes-256-cbc -K $encrypted_f7c81758bb4c_key -iv $encrypted_f7c81758bb4c_iv -in travis-ci.json.enc -out creds/travis-ci.json -d
- sudo apt-get update
- sudo apt-get install -y python3-pip
- pip3 install pytest
script:
- ./bin/deploy
